
.define SHOWTIMING 0

; vectors.s
.global reset

; cleanup.s
.global cleartia

; logodraw
.global logodraw

; charset for scroller
.global charset

; tables for scroller
.global text
.global powlist
.global colortab1
.global colortab2
.global bgofftab

.global scrollerstart
.global calcscroll
.global calcscrollwait

.global beamrider
.global calcbeamrider

.global Logo_PF0
.global Logo_PF1
.global Logo_PF2
.global Logo_PF3
.global Logo_PF4
.global Logo_PF5
